name: Employeeshift Deployment

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: yarn build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
        
        # This job is to cache the node modules in order to reduce the time it would take to run
      - name: Use cached node_modules
        uses: c-hive/gha-yarn-cache@v2
        with:
         directory: client
         
         #this job installs intalls yarn dependencies on the github runner
         #and also to build the static files that would be transferred to server later
      - name: install Dependencies
        run: |
          yarn install
          cd client
          yarn install
          yarn build
          
          
        # in the server your normal workflow except omitting yarn build
      - name: Git Pull on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOSTNAME }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /var/www/zc_plugin_company_shift/
            git stash
            git fetch --all
            git reset --hard origin/dev
            git pull origin dev
            yarn install
            cd client
            yarn install
          
       
        # this job copies the build folder from GitHub runners to the server with sftp, make sure the paths are correct      
      - name: Copy build to server
        uses: Creepios/sftp-action@v1.0.1
        with:
          username: ${{ secrets.SSH_USERNAME }}
          host: ${{ secrets.SSH_HOSTNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          localPath: './client/build/'
          remotePath: '/var/www/zc_plugin_company_shift/client/
          
          
        # this job ensures your processes are restarted after the process to serve your app
      - name: Restart pm2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOSTNAME }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /var/www/zc_plugin_company_shift/server
            sudo pm2 start 
            sudo pm2 list
            sudo pm2 restart all
