

name: Continuous Integration and Deployment Pipeline for Company Shift

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ dev ]

  pull_request:
    branches: [ dev ]
    types: [ closed ]



  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
#   This workflow contains a single job called "test and build"
#   test:                           #Test Job 
#     runs-on: ubuntu-latest        #Type of Machine Needed to Run the Job
#     strategy:
#       matrix:
#         node-version: [14.x]      #Set-up Node 
#     steps:
#       - uses: actions/checkout@v2 #Checks-out Repository so that workflow can access it
#       - name: Use Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v1
#         with:
#           node-version: ${{ matrix.node-version }}
#       - run: yarn install          #Install Dependencies
#       - run: yarn test             #Trigger Automated Test

  build:
#     needs: test
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Exec remote commands via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOSTNAME }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /var/www/zc_plugin_company_shift/
            cd server
            sudo yarn install
            sudo yarn run build
            sudo pm2 restart server
